# Generated by Django 4.2 on 2023-04-11 03:45

from django.db import migrations, models
import django.db.models.deletion
import warehouseApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.CharField(default=warehouseApp.models.generate_primary_key, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='warehouseApp.base')),
                ('quantity', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='warehouseMedia')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseApp.brand')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseApp.position')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseApp.producttype')),
            ],
            bases=('warehouseApp.base',),
        ),
    ]
